# Dockerfile for lazyslobs spring boot web application's backend
FROM openjdk:11-jdk
FROM mysql/mysql-server:latest
FROM ubuntu:latest

# open port 8080 for webserver
EXPOSE 8080

# for jre installation
RUN mkdir -p /usr/share/man/man1

# install necessary packages
RUN apt-get update
RUN apt-get install -y nano
RUN apt-get install -y nodejs
RUN apt-get install -y maven
RUN apt-get install -y git

# clone github repo
RUN git clone https://github.com/koumi15cancer/Lazy-Slobs---Group-1

# maven clean and install
RUN cd Lazy-Slobs---Group-1 && mvn clean && mvn install

# since application.properties need to have match IP with the machine
# we will stop at mvn clean and mvn install
# run the back end webserver
# RUN cd Lazy-Slobs---Group-1/target && java -jar LazySlob-0.0.1-SNAPSHOT.war
